// A good reference for midi key numbers:
// http://www.somascape.org/midi/basic/notes.html

const keys = [
  { id : 39, name : 'e0', key: 'e', octave: 1, sharp: false, flat: true,  through:true,  under:false, over:false, bass: true  },
  { id : 40, name : 'e0', key: 'e', octave: 1, sharp: false, flat: false, through:true,  under:false, over:false, bass: true  },
  { id : 41, name : 'f0', key: 'f', octave: 1, sharp: false, flat: false, through:false, under:false, over:false, bass: true  },
  { id : 42, name : 'f0', key: 'f', octave: 1, sharp: true,  flat: false, through:false, under:false, over:false, bass: true  },
  { id : 43, name : 'g0', key: 'g', octave: 1, sharp: false, flat: false, through:false, under:false, over:false, bass: true  },
  { id : 44, name : 'a1', key: 'a', octave: 1, sharp: false, flat: true,  through:false, under:false, over:false, bass: true  },
  { id : 45, name : 'a1', key: 'a', octave: 1, sharp: false, flat: false, through:false, under:false, over:false, bass: true  },
  { id : 46, name : 'b1', key: 'b', octave: 1, sharp: false, flat: true,  through:false, under:false, over:false, bass: true  },
  { id : 47, name : 'b1', key: 'b', octave: 1, sharp: false, flat: false, through:false, under:false, over:false, bass: true  },
  { id : 48, name : 'c2', key: 'c', octave: 2, sharp: false, flat: false, through:false, under:false, over:false, bass: true  },
  { id : 49, name : 'c2', key: 'c', octave: 2, sharp: true,  flat: false, through:false, under:false, over:false, bass: true  },
  { id : 50, name : 'd2', key: 'd', octave: 2, sharp: false, flat: false, through:false, under:false, over:false, bass: true  },
  { id : 51, name : 'e2', key: 'e', octave: 2, sharp: false, flat: true,  through:false, under:false, over:false, bass: true  },
  { id : 52, name : 'e2', key: 'e', octave: 2, sharp: false, flat: false, through:false, under:false, over:false, bass: true  },
  { id : 53, name : 'f2', key: 'f', octave: 2, sharp: false, flat: false, through:false, under:false, over:false, bass: true  },
  { id : 54, name : 'f2', key: 'f', octave: 2, sharp: true,  flat: false, through:false, under:false, over:false, bass: true  },
  { id : 55, name : 'g2', key: 'g', octave: 2, sharp: false, flat: false, through:false, under:false, over:false, bass: true  },
  { id : 56, name : 'a2', key: 'a', octave: 2, sharp: false, flat: true,  through:false, under:false, over:false, bass: true  },
  { id : 57, name : 'a2', key: 'a', octave: 2, sharp: false, flat: false, through:false, under:false, over:false, bass: true  },
  { id : 58, name : 'b2', key: 'b', octave: 2, sharp: false, flat: true,  through:false, under:false, over:false, bass: true  },
  { id : 59, name : 'b2', key: 'b', octave: 2, sharp: false, flat: false, through:false, under:false, over:false, bass: true  },
  { id : 60, name : 'c3', key: 'c', octave: 3, sharp: false, flat: false, through:true,  under:false, over:false, bass: false },
  { id : 61, name : 'c3', key: 'c', octave: 3, sharp: true,  flat: false, through:true,  under:false, over:false, bass: false },
  { id : 62, name : 'd3', key: 'd', octave: 3, sharp: false, flat: false, through:false, under:false, over:false, bass: false },
  { id : 63, name : 'e3', key: 'e', octave: 3, sharp: false, flat: true,  through:false, under:false, over:false, bass: false },
  { id : 64, name : 'e3', key: 'e', octave: 3, sharp: false, flat: false, through:false, under:false, over:false, bass: false },
  { id : 65, name : 'f3', key: 'f', octave: 3, sharp: false, flat: false, through:false, under:false, over:false, bass: false },
  { id : 66, name : 'f3', key: 'f', octave: 3, sharp: true,  flat: false, through:false, under:false, over:false, bass: false },
  { id : 67, name : 'g3', key: 'g', octave: 3, sharp: false, flat: false, through:false, under:false, over:false, bass: false },
  { id : 68, name : 'a3', key: 'a', octave: 3, sharp: false, flat: true,  through:false, under:false, over:false, bass: false },
  { id : 69, name : 'a3', key: 'a', octave: 3, sharp: false, flat: false, through:false, under:false, over:false, bass: false },
  { id : 70, name : 'b3', key: 'b', octave: 3, sharp: false, flat: true,  through:false, under:false, over:false, bass: false },
  { id : 71, name : 'b3', key: 'b', octave: 3, sharp: false, flat: false, through:false, under:false, over:false, bass: false },
  { id : 72, name : 'c4', key: 'c', octave: 4, sharp: false, flat: false, through:false, under:false, over:false, bass: false },
  { id : 73, name : 'c4', key: 'c', octave: 4, sharp: true,  flat: false, through:false, under:false, over:false, bass: false },
  { id : 74, name : 'd4', key: 'd', octave: 4, sharp: false, flat: false, through:false, under:false, over:false, bass: false },
  { id : 75, name : 'e4', key: 'e', octave: 4, sharp: false, flat: true,  through:false, under:false, over:false, bass: false },
  { id : 76, name : 'e4', key: 'e', octave: 4, sharp: false, flat: false, through:false, under:false, over:false, bass: false },
  { id : 77, name : 'f4', key: 'f', octave: 4, sharp: false, flat: false, through:false, under:false, over:false, bass: false },
  { id : 78, name : 'f4', key: 'f', octave: 4, sharp: true,  flat: false, through:false, under:false, over:false, bass: false },
  { id : 79, name : 'g4', key: 'g', octave: 4, sharp: false, flat: false, through:false, under:false, over:false, bass: false },
  { id : 80, name : 'a4', key: 'a', octave: 4, sharp: false, flat: true,  through:true,  under:false, over:false,  bass: false },
  { id : 81, name : 'a4', key: 'a', octave: 4, sharp: false, flat: false, through:true,  under:false, over:false,  bass: false },
];

const signatures = 
[
  { id: 'CM',  major: 'C',        minor: 'A',       sharps: [], flats: [] },
  { id: 'GM',  major: 'G',        minor: 'E',       sharps: [ 'f' ], flats: [] },
  { id: 'DM',  major: 'D',        minor: 'B',       sharps: [ 'f', 'c' ], flats: [] },
  { id: 'AM',  major: 'A',        minor: 'F-sharp', sharps: [ 'f', 'c', 'g' ], flats: [] },
  { id: 'EM',  major: 'E',        minor: 'C-sharp', sharps: [ 'f', 'c', 'g', 'd' ], flats: [] },
  { id: 'BM',  major: 'B',        minor: 'G-sharp', sharps: [ 'f', 'c', 'g', 'd', 'a' ], flats: [] },
  { id: 'FsM', major: 'F-sharp',  minor: 'D-sharp', sharps: [ 'f', 'c', 'g', 'd', 'a', 'e' ], flats: [] },
  { id: 'CsM', major: 'C-sharp',  minor: 'A-sharp', sharps: [ 'f', 'c', 'g', 'd', 'a', 'e', 'b' ], flats: [] },
  { id: 'FM',  major: 'F',        minor: 'D',       sharps: [], flats: [ 'b' ] },
  { id: 'BfM', major: 'B-flat',   minor: 'G',       sharps: [], flats: [ 'b', 'e' ] },
  { id: 'EfM', major: 'E-flat',   minor: 'C',       sharps: [], flats: [ 'b', 'e', 'a' ] },
  { id: 'AfM', major: 'A-flat',   minor: 'F',       sharps: [], flats: [ 'b', 'e', 'a', 'd' ] },
  { id: 'DfM', major: 'D-flat',   minor: 'B-flat',  sharps: [], flats: [ 'b', 'e', 'a', 'd', 'g' ] },
  { id: 'GfM', major: 'G-flat',   minor: 'E-flat',  sharps: [], flats: [ 'b', 'e', 'a', 'd', 'g', 'c' ] },
  { id: 'CfM', major: 'C-flat',   minor: 'A-flat',  sharps: [], flats: [ 'b', 'e', 'a', 'd', 'g', 'c', 'f' ] },
];

module.exports = { keys, signatures };