// A good reference for midi key numbers:
// http://www.somascape.org/midi/basic/notes.html

const keys = [
  { id : 39, name : 'e0',  sharp: false, flat: true,  ledger: true,  bass: true  },
  { id : 40, name : 'e0',  sharp: false, flat: false, ledger: true,  bass: true  },
  { id : 41, name : 'f0',  sharp: false, flat: false, ledger: false, bass: true  },
  { id : 42, name : 'f0',  sharp: true,  flat: false, ledger: false, bass: true  },
  { id : 43, name : 'g0',  sharp: false, flat: false, ledger: false, bass: true  },
  { id : 44, name : 'a1',  sharp: false, flat: true,  ledger: false, bass: true  },
  { id : 45, name : 'a1',  sharp: false, flat: false, ledger: false, bass: true  },
  { id : 46, name : 'b1',  sharp: false, flat: true,  ledger: false, bass: true  },
  { id : 47, name : 'b1',  sharp: false, flat: false, ledger: false, bass: true  },
  { id : 48, name : 'c1',  sharp: false, flat: false, ledger: false, bass: true  },
  { id : 49, name : 'c1',  sharp: true,  flat: false, ledger: false, bass: true  },
  { id : 50, name : 'd1',  sharp: false, flat: false, ledger: false, bass: true  },
  { id : 51, name : 'e1',  sharp: false, flat: true,  ledger: false, bass: true  },
  { id : 52, name : 'e1',  sharp: false, flat: false, ledger: false, bass: true  },
  { id : 53, name : 'f1',  sharp: false, flat: false, ledger: false, bass: true  },
  { id : 54, name : 'f1',  sharp: true,  flat: false, ledger: false, bass: true  },
  { id : 55, name : 'g1',  sharp: false, flat: false, ledger: false, bass: true  },
  { id : 56, name : 'a2',  sharp: false, flat: true,  ledger: false, bass: true  },
  { id : 57, name : 'a2',  sharp: false, flat: false, ledger: false, bass: true  },
  { id : 58, name : 'b2',  sharp: false, flat: true,  ledger: false, bass: true  },
  { id : 59, name : 'b2',  sharp: false, flat: false, ledger: false, bass: true  },
  { id : 60, name : 'c3',  sharp: false, flat: false, ledger: true,  bass: false },
  { id : 61, name : 'c3',  sharp: true,  flat: false, ledger: true,  bass: false },
  { id : 62, name : 'd3',  sharp: false, flat: false, ledger: false, bass: false },
  { id : 63, name : 'e3',  sharp: false, flat: true,  ledger: false, bass: false },
  { id : 64, name : 'e3',  sharp: false, flat: false, ledger: false, bass: false },
  { id : 65, name : 'f3',  sharp: false, flat: false, ledger: false, bass: false },
  { id : 66, name : 'f3',  sharp: true,  flat: false, ledger: false, bass: false },
  { id : 67, name : 'g3',  sharp: false, flat: false, ledger: false, bass: false },
  { id : 68, name : 'a3',  sharp: false, flat: true,  ledger: false, bass: false },
  { id : 69, name : 'a3',  sharp: false, flat: false, ledger: false, bass: false },
  { id : 70, name : 'b3',  sharp: false, flat: true,  ledger: false, bass: false },
  { id : 71, name : 'b3',  sharp: false, flat: false, ledger: false, bass: false },
  { id : 72, name : 'c4',  sharp: false, flat: false, ledger: false, bass: false },
  { id : 73, name : 'c4',  sharp: true,  flat: false, ledger: false, bass: false },
  { id : 74, name : 'd4',  sharp: false, flat: false, ledger: false, bass: false },
  { id : 75, name : 'e4',  sharp: false, flat: true,  ledger: false, bass: false },
  { id : 76, name : 'e4',  sharp: false, flat: false, ledger: false, bass: false },
  { id : 77, name : 'f4',  sharp: false, flat: false, ledger: false, bass: false },
  { id : 78, name : 'f4',  sharp: true,  flat: false, ledger: false, bass: false },
  { id : 79, name : 'g4',  sharp: false, flat: false, ledger: false, bass: false },
  { id : 80, name : 'a4',  sharp: false, flat: true,  ledger: true,  bass: false },
  { id : 81, name : 'a4',  sharp: false, flat: false, ledger: true,  bass: false },
];

module.exports = keys;